import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import Hero from "@/components/Hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);

  const getData = async () => {
    const getData = await fetch("/api/hello", { method: "POST", body: "data" });
    const res = await getData.json();
    setData(res);
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <p>This is an API testing area</p>
        <p>Status: {data && data.name ? "Success" : "Fail"}</p>
        <h1>Output: {data.name}</h1>
        <Hero src={data.vidSrc} />
      </main>
    </>
  );
}
